# Generated by Django 5.0.1 on 2024-02-22 19:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('school_gps_coordinates', models.CharField(max_length=150)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_of_location', models.CharField(max_length=100)),
                ('hostel_name', models.CharField(max_length=100)),
                ('hostel_contact', models.CharField(max_length=13)),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('duration_of_rent', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=10)),
                ('display_image', models.ImageField(upload_to='hostel/display/images')),
                ('hostel_gps_coordinates', models.CharField(max_length=100)),
                ('account_number', models.PositiveIntegerField()),
                ('account_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('publish', models.BooleanField(default=False)),
                ('amenities', models.ManyToManyField(to='hostel.amenities')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school_located', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.school')),
            ],
        ),
        migrations.CreateModel(
            name='HostelPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='hostels/images')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('number_available', models.PositiveIntegerField()),
                ('room_capacity', models.PositiveIntegerField()),
                ('cost', models.FloatField()),
                ('simple_description', models.TextField(blank=True, null=True)),
                ('occupant_sex', models.CharField(blank=True, max_length=15, null=True)),
                ('has_occupant', models.BooleanField(default=False)),
                ('has_half_payment', models.BooleanField(default=False)),
                ('is_full', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
    ]
