# Generated by Django 5.0.1 on 2024-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_room_has_half_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupant_sex',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
